# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
  displayName: 'Use Python 3.7'

- script: |
    python -m pip install --upgrade pip
    pip install setuptools wheel twine Firo
  displayName: 'Install dependencies'

- script: |
    cd test
    python test.py
    rm Test.db
  displayName: '1/3 Running Tests...'

- script: |
    python setup.py sdist bdist_wheel
  displayName: '2/3 Packaging module...'

- script: |
    python -m twine upload -u PeeledFruitStudios -p $(pypi-code) dist/*
  displayName: '3/3 Uploading to PyPi'
